### ISSUE TITLE
Sorry, you are not allowed to create resources.

### ISSUE THREAD

**Issue by idrinktomakepeopleinteresting** [woocommerce/wc-api-python#17]
Hi,

Having a bit of an issue.

```
wcapi = API(
    url="http://website.com/",
    consumer_key="ck_XXX",
    consumer_secret="cs_XXX",
    wp_api=True,
    version="wc/v1"
)

woo_post_data = {...}

print(wcapi.post("products", woo_post_data).json())

{u'message': u'Sorry, you are not allowed to create resources.', u'code': u'woocommerce_rest_cannot_create', u'data': {u'status': 401}}
```

Using latest woocommerce & wordpress and latest wrapper.

It's over http and I've tried via cURL as well, as you've mentioned in a previous issue.

```
curl -k -u consumer_key:consumer_secret https://www.example.com/wp-json/wc/v1/orders
curl -k -g "https://www.example.com/wp-json/wc/v1/orders?consumer_key=123&consumer_secret=abc"
```
^ and got the same response.

```
API(
    url="https://kashalife.net/",
    consumer_key="ck_16c59a1a0693c2723928830da52a30640c2311fd",
    consumer_secret="cs_0b4e0f17741e024b31d0ef799257b972db473305",
    wp_api=False,
    verify_ssl=False,
    version="v3",
    query_string_auth=True
)
```
^ Tried that:

`{u'errors': [{u'message': u'oauth_consumer_key parameter is missing', u'code': u'woocommerce_api_authentication_error'}]}`

Any suggestions?

Hope to hear from you soon,

Thank you.

**Comment by claudiosmweb** [comment]
Not an issue with this wrapper.
For what I'm seeing, look that is wroking just fine, maybe you user don't really have permissions to create customers.
Need to be a Shop Manager ou a Administrator.
