### ISSUE TITLE
put order returns 404

### ISSUE THREAD

**Issue by smitthakkar96** [woocommerce/wc-api-python#20]

**Comment by claudiosmweb** [comment]
PUT orders works just fine.
And this wrapper could not cause any issue making return 404.

**Comment by smitthakkar96** [comment]
```
    orderId = request.args.get('orderId')
    store = request.args.get('store')
    if store == 'LY':
        print LY_api.put('orders/{}'.format(orderId), {"status" : "cancelled"}).status_code
        return jsonify({"response" : LY_api.put('orders/{}'.format(orderId), {"status" : "cancelled"}).json()})
    elif store == 'WD':
        pass
        return jsonify({"response" : WD_api.put('orders'.format(orderId), {"status" : "cancelled"}).text})
        return WD_api.put('orders', {"status" : "cancelled"}).text
    else:
        return jsonify({"response" : "store not found"}), 400

```

Above is the code which calls api

**Comment by claudiosmweb** [comment]
Your code is wrong, since we don't have any route for `PUT orders/` You need to pass an ID.

Here the wrong code:

```
        return jsonify({"response" : WD_api.put('orders'.format(orderId), {"status" : "cancelled"}).text})
        return WD_api.put('orders', {"status" : "cancelled"}).text
```

**Comment by smitthakkar96** [comment]
@claudiosmweb I am passing the Id as you can see in line 3, what is wrong in my code?

**Comment by claudiosmweb** [comment]
@smitthakkar96 Thanks for change the code...

Well maybe passing the wrong ID.
Still please understand that this IS NOT an issue in this wrapper, if is returning 404 it's because the WooCommerce REST API is returning 404.
And here is not a channel for support about the REST API.
