### ISSUE TITLE
Woocommerce REST API Docs Not Found

### ISSUE THREAD

**Issue by CortexNe** [woocommerce/wc-api-python#21]
Hi, Im trying to inquire about Woocommerce REST API Authentication but this link does not work 
http://woothemes.github.io/woocommerce-rest-api-docs/#authentication

i cant approve my sites authentication, and getting this error: An error occurred in the request and at the time were unable to send the consumer data

thanks a lot

**Comment by claudiosmweb** [comment]
New address: https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication

**Comment by gwuah** [comment]
I' facing the same problem. (testing locally though)

**Comment by shubhamkushwahsk** [comment]
I was having the same issue as well, and in my case, the return_url on my backend server was accepting `GET` requests, I changed it to `POST`, and everything worked perfectly. I hope it helps!
