### ISSUE TITLE
Woocommcerce REST API URLs not working

### ISSUE THREAD

**Issue by CortexNe** [woocommerce/wc-api-python#22]
From one moment to another i could see the Json data of the site im workning on, to use it on an android app, when its writen with the domain name of the ssl certificate it appears this `{
code: "woocommerce_rest_cannot_view",
message: "Sorry, you cannot list resources.",
data: {
status: 401
}
}` 

but when i use the ip adress instead, it works fine but it seems the site is not secured,
when i try to authenticate it apears this error:  "An error occurred in the request and at the time were unable to send the consumer data"
its neede for this to be ready as soon, how can i solve this, thanks a lot

**Comment by claudiosanches** [comment]
Don't looks like an issue with this REST API lib.
If you have questions about the WooCommerce REST API, you should ask in the WooCommerce support forum: https://wordpress.org/support/plugin/woocommerce
