### ISSUE TITLE
Loading next results

### ISSUE THREAD

**Issue by jdruiter** [woocommerce/wc-api-python#24]
Woocommere API wc/v1 offers a next url. 

With a minor modification this next link could be called with wcapi.get('orders', nextLink)

The code needs to be updated for this functionality. 

Example:
http://www.adventuretickets.nl/wp-json/wc/v1/orders?oauth_consumer_key=XXX&oauth_timestamp=1484423197&oauth_nonce=YYY&oauth_signature_method=HMAC-SHA256&oauth_signature=ZZZ&page=2

**Comment by claudiosanches** [comment]
You can just use `wcapi.get('orders?page=2')`.
