### ISSUE TITLE
timestamp error

### ISSUE THREAD

**Issue by tiger360** [woocommerce/wc-api-python#25]
Hello,

I have this error code : 
{'code': 'woocommerce_rest_authentication_error', 'data': {'status': 401}, 'message': 'Invalid timestamp.'}

I am sure it's the right keys and url because I run the code on the same server where the wordpress is installed andd it works.
But when I run this code from my personal computer, I constantly have the error with the timestamp.

And I'm using this
wcapi = API(
    url="url",
    consumer_key="xxxx",
    consumer_secret="xx",
    wp_api=True,
    version="wc/v1"
)

Thanks

**Comment by claudiosanches** [comment]
This happens when have a difference between timezones from your server and your app.
We need to update this library to accept custom timezones, probably I'll be doing it next week.
Thanks for reporting it.
