### ISSUE TITLE
Product categories with backslashes in the title don't show up in API search results

### ISSUE THREAD

**Issue by slukin1** [woocommerce/wc-api-python#26]
Category name = 'Система Linux \Unix'
wcapi.get("products/categories?search=%s" % ('Система Linux \Unix')).json()
not return existed result
Escaping u'Система Linux \Unix' not return existed result,
urllib.quote_plus(u'Система Linux \Unix') not return existed result
quote(u'Система Linux \Unix') not return existed result

Also problem if name of category with forward slash, example category name: '/n software' and if ampersand in category name, example: 'Tools&Comps'

**Comment by claudiosanches** [comment]
Just use category slugs and this is not an issue with this REST API wrapper.
