### ISSUE TITLE
not get all products

### ISSUE THREAD

**Issue by MikeSoft** [woocommerce/wc-api-python#27]
the next code
`
import json
from woocommerce import API

wcapi = API(
    url="xxxxxxxxxxxxx",
    consumer_key="xxxxxxxxxxxx",
    consumer_secret="xxxxxxxxxxxx"
)

r = wcapi.get("products")
print r.text
`

just get 10 products, and where are the others? o.O

**Comment by claudiosanches** [comment]
This is not an issue in this library and in the REST API documentation talks about pagination and items for request.
Have you read the REST API docs?
https://woocommerce.github.io/woocommerce-rest-api-docs/

**Comment by jroqueweb** [comment]
Reopen this issue.
Even passing the filter by querystring to api does not accept:

wcapi = API(
    url="https://primosupermercado.com.br",
    consumer_key="ck_xxxx",
    consumer_secret="cs_xxxx",
    verify_ssl=False
)
response = wcapi.get("products?per_page=12")

**Comment by claudiosanches** [comment]
@jroqueweb because this depends on the versions that you are using of the REST API, not all versions works with `per_page`.
