### ISSUE TITLE
REST authentication error

### ISSUE THREAD

**Issue by mar5** [woocommerce/wc-api-python#28]
Hello,

Having truble authenticating with rest api, all the time I get the same error. 

Wordpress 4.7.4
Woocommerce 3.0.5
Python 2.7.13

```
from woocommerce import API

wcapi = API(
    url="http://XYZ/~aclassi2/note/",
    consumer_key="ck_YYY",
    consumer_secret="cs_XXX",
    wp_api=True,
    version="wc/v2",
    verify_ssl=False,
    query_string_auth=True
)

{"code":"woocommerce_rest_authentication_error","message":"Invalid signature - provided signature does not match.","data":{"status":401}}

```
When I use Postman, it works fine. I also tested with nodeJS, is maybe python lib broken?

**Comment by claudiosanches** [comment]
Are you using Postman doing a oAuth1.0a authentication?
In my tests it works just fine.

**Comment by mar5** [comment]
Yeah, oAuth1.0 authentication via Postman, but not with python.

**Comment by claudiosanches** [comment]
Not credentials, but I need more details, just it is not enough for try reproduce the error.

**Comment by mar5** [comment]
I am glad to provide you more information. Can you tell me what information do you need?

**Comment by mar5** [comment]
You can close the issue, it works. I was using IP to connect to server now when I switched to domain it works. Maybe parsing is not working as expected or something else was wrong.
