### ISSUE TITLE
Download all Products

### ISSUE THREAD

**Issue by eduaero** [woocommerce/wc-api-python#36]
First thank you very much for this amazing work!!

I am trying to get all the products and I don' really know how to do it.

I have tried to do

wcapi.get('products?per_page=100')
But I have more than 100 products

Furthermore, I have tried to introduce the pagination as it is recommended in the manual, but it does not say how to introduce it in the code...

I would love if someone could help me out with this.

Yours sincerely,

**Comment by eduaero** [comment]
Thank you jlegido

What you have written it is not recognized.

However it would do the same as:
wcapi.get('products?per_page=100')

My problem is that I have, lets say 300 products and the maximum products per_page is 100.
wcapi.get('products?per_page=200') --> Do not work as 200>100

Furthermore I cannot ask for:

wcapi.get('products?per_page=100?page=2')
As it tells me that after per_page= everything should be an integer.

Any help would be really really welcome as I really need to get all the products downloaded.

Thank you very much 👍

**Comment by eduaero** [comment]
I have done it on the following way. I hope that someone can find it useful:

page=0
while True:
    page=page+1
    str=("products?page=%d") % page
    r=wcapi.get(str)
    r_text=r.text
    parsed = json.loads(r_text)
    file=json.dumps(parsed, indent=4)
    file_json = json.loads(file)
    if file_json.__len__()<10:
        break

**Comment by sambarza** [comment]
Just for share, this:
`wcapi.get('products?per_page=100?page=2')`

the second ? should be &:
`wcapi.get('products?per_page=100&page=2')`
