### ISSUE TITLE
Download all products in specific language (WPML)

### ISSUE THREAD

**Issue by LucSpan** [woocommerce/wc-api-python#39]
My WooCommerce has 3 different languages: default lang is French. 

`wcapi.get('products/?per_page=100').json()`

gives up to 100 products in the default language. 

`wcapi.get('products/?lang=en').json()`

gives up to 10 products in the English language. 

How do I combine to two, such that I get up to 100 products in the English language?

**Comment by claudiosanches** [comment]
Just use `&` to combination both, like any other query string in URLs.
