### ISSUE TITLE
per_page and all integer parameters does't works

### ISSUE THREAD

**Issue by Edge-Rider** [woocommerce/wc-api-python#44]
While trying to get product/categories from Woocommerce I got this error:
"per_page is not of type integer"

my code:

wcapi = API(
url="http://my_web.site",
consumer_key="ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
consumer_secret="cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
version="wc/v3"
)

categories = wcapi.get("products/categories/?per_page=1").json()

get the same error for all integer parameters

**Comment by Edge-Rider** [comment]
found solution:
my code:

wcapi = API(
url="http://my_web.site",
consumer_key="ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
consumer_secret="cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
version="wc/v3"
)
parameter = {}
parameter[per_page] = 1
categories = wcapi.get("products/categories/", params=parameter).json()
would be useful for newbies like me if reported examples on documentation

**Comment by mdergueche** [comment]
Thank you Edge rider for this. I was looking for hours to how to do this. I storngly recomend to add indeed one example about the parameters. It is not obvious and I was looking into the code too to see how I pass **KWARGS arguments

**Comment by quentin-oyopi** [comment]
Same here, thank you @Edge-Rider for this example.

@mdergueche 
>  I storngly recomend to add indeed one example about the parameters. It is not obvious and I was looking into the code too to see how I pass **KWARGS arguments
Definitely !

**Comment by claudiosanches** [comment]
I updated some examples of it. Before WordPress didn't make validation strong like that, and also seems like under HTTPS this is not a problem. Still is better use `params` instead of just passing by the endpoint.

**Comment by AndriiBukhanenko** [comment]
@Edge-Rider Thanks !!!

**Comment by IAmBotmaker** [comment]
> found solution:
> my code:
> 
> wcapi = API(
> url="http://my_web.site",
> consumer_key="ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
> consumer_secret="cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
> version="wc/v3"
> )
> parameter = {}
> parameter[per_page] = 1
> categories = wcapi.get("products/categories/", params=parameter).json()
> would be useful for newbies like me if reported examples on documentation

Thank you very much, Edge-Rider!
For newbies it would be totally right to say that the correct use for dictionary item would be:
parameter['per_page'] = 1
or
parameter["per_page"] = 1
