### ISSUE TITLE
Can't delete categories - 'force': 'true? is not of type boolean'

### ISSUE THREAD

**Issue by mircosantori** [woocommerce/wc-api-python#46]
There might be an issue with the delete method or anything related to the rest code.
Here is the error message when I try to delete a category : 
```
{
  'code': 'rest_invalid_param', 
  'message': 'Invalid parameter(s): force', 'data': {
    'status': 400, 
    'params': {
      'force': 'true? is not of type boolean.'
      }
  }
}
```

and my code (tried few variations) : 
```
wcapi.delete("products/categories/19?force=true).json()
wcapi.delete("products/categories/19).json()
```

Please help!

**Comment by Bimblis** [comment]
Same problem

**Comment by mircosantori** [comment]
> Same problem

if you are working locally, try to self-generate a ssl certificate and use https. It fixed my issue, even though the message we get doesnt help that much.

let me know how it goes @Bimblis

**Comment by claudiosanches** [comment]
Seems like WordPress is forcing validation, I could solve it with:

```python
wcapi.delete("products/categories/19", params={"force": True}).json()
```

I also updated Python examples in the REST API docs.
