### ISSUE TITLE
Get product ID from SKU

### ISSUE THREAD

**Issue by albertoZurini** [woocommerce/wc-api-python#49]
I've already tried ```wcapi.get('products?filter[sku]="{MY_SKU}')```, but it returns a list with the top 10 products in my ecommerce.

**Comment by albertoZurini** [comment]
Solved by sending the request to ```https://www.glerie.it/wc-api/v3/products?filter[sku]={MY_SKU}```

**Comment by albertoZurini** [comment]
Solved sending the request to ```https://SITE/wc-api/v3/products?filter[sku]={MY_SKU}```

**Comment by Vincenzoferrara** [comment]
also works with  `wcapi.get("products",params={'id': '1'}).json()`
