### ISSUE TITLE
How to speed up the response after calling Woocommerce APIs? 

### ISSUE THREAD

**Issue by juno249** [woocommerce/wc-api-python#52]
I have an issue with the speed of the Woocommerce REST API. What I’m trying to do is import about 10k products (~65k variations) in total as fast as possible. The issue I’m running into is it seems that WordPress loads core, plugins and themes when the REST API is called.

**Comment by claudiosanches** [comment]
Hello, this need to be improved in WordPress and WooCommerce side, I'm happy to reply any questions about this REST API library, but for WooCommerce and WordPress questions you could try: https://wordpress.org/support/plugin/woocommerce/
