### ISSUE TITLE
List Orders params does not support ISO compliant date without time

### ISSUE THREAD

**Issue by htpeter** [woocommerce/wc-api-python#54]
When making a request to the `orders` endpoint, I found that some `params` (`after` and `before`) which are supposed to take an ISO8601 compliant date do not run unless the user also includes the time. 

The error occurs when I run the following command:
```
resp = wcapi.get("orders", params = {"per_page" : "100", "page" : 1, "after" : "2020-07-31"})
resp.content
```
with this error returned to the user in `resp.content`
```
(b'{"code":"rest_invalid_param","message":"Invalid parameter(s): after","data":'
 b'{"status":400,"params":{"after":"Invalid date."}}}')
```

But I am able to get a valid response by extending the date to also include time:
```
resp = wcapi.get("orders", params = {"per_page" : "100", "page" : 1, "after" : "2020-07-31T23:23:59"})
```

**Comment by claudiosanches** [comment]
Hello @htpeter, thanks for reporting it, but this issue and the result you are reading with the `rest_invalid_param` code is coming from your WordPress and WooCommerce installation, this issue isn't related to this REST API library. I suggest you to try help in https://wordpress.org/support/plugin/woocommerce/
