### ISSUE TITLE
Get category by name

### ISSUE THREAD

**Issue by pankaj-webkul** [woocommerce/wc-api-python#55]
When creating a category, if already exists, how to get category id?

**Comment by DeanForde** [comment]
print(wcapi.get("products/categories/", params={"name":cat.name}).json())

**Comment by claudiosanches** [comment]
@pankaj-webkul You can see how to fetch categories in WooCommerce's REST API documentation:

https://woocommerce.github.io/woocommerce-rest-api-docs/#product-categories

**Comment by iwkse** [comment]
Doesn't seem to be working with the current version. It works using "id" or "slug" as parameter though, but "name" gives all categories.

**Comment by Kennypurnomo** [comment]
> Doesn't seem to be working with the current version. It works using "id" or "slug" as parameter though, but "name" gives all categories.

Yes. I think using "name" as parameter is not working. Are you sure we can use the slug?

**Comment by iwkse** [comment]
Yes, I've tested the slug and it works.
