### ISSUE TITLE
error in orders API

### ISSUE THREAD

**Issue by yamins81** [woocommerce/wc-api-python#58]
Sometimes when pulling orders from more then two months ago, sometimes the end of the list of orders looks like:

[actual orders ...
 'code',
 'message',
 'data',
 'additional_errors']

It's as if the order database can't pull the furthest-back orders properly.  Do you know what might be causing this?  I haven't seen any documentation that mentions this type of output.

**Comment by claudiosanches** [comment]
Hello @yamins81, thank you for reporting it, but those are results from the WooCommerce REST API, I'm happy to reply any question about this Python library, but for help about the WooCommerce REST API you could try https://wordpress.org/support/plugin/woocommerce/
