### ISSUE TITLE
Generating the authentication endpoint, popup not appearing

### ISSUE THREAD

**Issue by MaximilianSamLickeAgdur** [woocommerce/wc-api-python#59]
I am trying to create the automate authentication endpoint for my app, it seems to work fine in terms of the post request to create it but the pop-up where i would connect to/accept the app does not appear, under which url does this popup usually present itself? - the request returns 200 and css/html that seems on point with what i would expect to be the popup... just cant find the actual popup itself when logging in to my woocommerce account..anyone?

**Comment by claudiosanches** [comment]
Hello, this library doesn't produce any popup. If you want to create a authentication follow you can follow this documentation: https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication (see "Auto generating API keys using our Application Authentication Endpoint").
But as you could notice, not WooCommerce or this library creates any popup.
