### ISSUE TITLE
verify_ssl=False is being ingnore while uploading images from/to same server

### ISSUE THREAD

**Issue by bigretromike** [woocommerce/wc-api-python#60]
While partially working it helps with errors like:
`'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1122)')))`

sadly as soon as I try to create product:
`wcapi.post("products", data=json_data)`

It throw error:
```
{"code":"woocommerce_product_image_upload_error","message":"Error getting remote image https:\/\/debian.local\/wp-content\/uploads\/2021\/01\/0_img-cache-39.jpg. Error: cURL error 60: SSL certificate problem: self signed certificate","data":{"status":400}}
```

When src url is pointing on same self-sign server there is error, to workaround it you could replace https to http in image urls.

Any chance to passthru the verify_ssl parameter to curl ?

**Comment by claudiosanches** [comment]
Hello, this error is from your WP installation, there's no means to disable it on your WordPress during a request, this library will not verify if you disable, but you'll need to also disable in your WP installation as well, if you intend to test like that in localhost.

**Comment by bigretromike** [comment]
Are you sure? The error is because i use self-sign certificate. Your command is not passing the right parameter to tell tool that it should ignore error and use given files as certificates. That has nothing to do with anything disabled on Wordpress instalation - because that workflawless on test lab with added selfsign certificates.

**Comment by iwkse** [comment]
@bigretromike Hi, I have the same issue and I thought I found the solution. I just want to test it locally with self-signed certificate as well. Any hint?

**Comment by iwkse** [comment]
I've solved it adding a filter like:
```
add_filter('https_ssl_verify', '__return_false');
```

**Comment by cc0adolf** [comment]
> I've solved it adding a filter like:
> 
> ```
> add_filter('https_ssl_verify', '__return_false');
> ```

What's the file where you add this?
